version: "3.8"
services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf/:/usr/local/etc/redis/redis.conf
    command: redis-server
  chrome:
    image: "browserless/chrome"
    ports:
      - 3000:3000
  app:
    build: .
    ports:
      - 1338:1338
