version: "3.8"
services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf/:/usr/local/etc/redis/redis.conf
    command: redis-server
  chrome:
    image: "browserless/chrome"
    environment:
      - CONNECTION_TIMEOUT=180000
      - MAX_CONCURRENT_SESSIONS=3
      - ENABLE_CORS=true
    ports:
      - 3000:3000
  app:
    build:
      context: .
    ports:
      - 1338:1338
      - 9229:9229
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
    depends_on:
      - redis
      - chrome
    volumes:
      - ./:/usr/app
    command: yarn dev
